version: '3.8'
services:

  # core-uilication & web server
  core-ui:
    container_name: core-ui
    build:
      context: .
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - "database"
    ports:
      - 8080:80
    networks:
      - core-uinetwork
  # Database
  database:
    container_name: coreui-db
    image: mysql:5.7-debian
    volumes:
      - core-uidbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: core-ui
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
    ports:
      - "33061:3306"
    networks:
      - core-uinetwork
  # Database management
  pma:
    image: phpmyadmin:5.1
    networks:
      - core-uinetwork
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=admin
      - PMA_PASSWORD=admin
      - PMA_PORT=3306
    depends_on:
      - database
    ports:
      - 8888:80

volumes:
  core-uidbdata:

networks:
  core-uinetwork: